apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: nginx
  template:
    metadata:
      labels: 
        app: {{ .Chart.Name }}
    spec: 
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tagOverride }}
          ports:
              containerPort: 80    