apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: {{ .Values.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.name }}
    spec: 
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tagOverride }}
          name: {{ .Values.name }}
          ports:
            - containerPort: {{ .Values.service.port }}   