---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: practice
  strategy: 
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
        - image: nginx:1.13
          name: nginx
          ports:
            - containerPort: 80    
---
apiVersion: v1
kind: Service
metadata:
  name: service-practice
spec:
  type: LoadBalancer
  selector:
    app: 
    - practice
    - my-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011